name: Build and deploy the Web App

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release

      - name: Publish to folder
        run: msbuild /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=FileSystem /p:publishUrl=./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: webapp
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: webapp

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "floralhaven" # Replace with your Azure Web App name
          publish-profile: ${{ secrets.FLORAL_HAVEN_PUBLISH_PROFILE }}
          package: ./webapp
